
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: admin
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # This will be the name of your development database
  database: rottenpotatoes_development

test:
  <<: *default
  # This will be the name of your test database
  database: rottenpotatoes_test


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  <<: *default
  database: rottenpotatoes
