more_movies = [
    { title: 'My Neighbor Totoro', rating: 'G', release_date: '16-Apr-1988' },
    { title: 'Green Book', rating: 'PG-13', release_date: '16-Nov-2018' },
    { title: 'Parasite', rating: 'R', release_date: '30-May-2019' },
    { title: 'Nomadland', rating: 'R', release_date: '19-Feb-2021' },
    { title: 'CODA', rating: 'PG-13', release_date: '13-Aug-2021' }
  ]
  
  top_100_movies = [
    { title: 'The Shawshank Redemption', rating: 'R', release_date: '14-Oct-1994' },
    { title: 'The Godfather', rating: 'R', release_date: '24-Mar-1972' },
    { title: 'The Dark Knight', rating: 'PG-13', release_date: '18-Jul-2008' },
    { title: 'The Godfather Part II', rating: 'R', release_date: '20-Dec-1974' },
    { title: '12 Angry Men', rating: 'Not Rated', release_date: '10-Apr-1957' },
    { title: "Schindler's List", rating: 'R', release_date: '04-Feb-1994' },
    { title: 'The Lord of the Rings: The Return of the King', rating: 'PG-13', release_date: '17-Dec-2003' },
    { title: 'Pulp Fiction', rating: 'R', release_date: '14-Oct-1994' },
    { title: 'The Lord of the Rings: The Fellowship of the Ring', rating: 'PG-13', release_date: '19-Dec-2001' },
    { title: 'The Good, the Bad and the Ugly', rating: 'Not Rated', release_date: '29-Dec-1967' },
    { title: 'Forrest Gump', rating: 'PG-13', release_date: '06-Jul-1994' },
    { title: 'Fight Club', rating: 'R', release_date: '15-Oct-1999' },
    { title: 'The Lord of the Rings: The Two Towers', rating: 'PG-13', release_date: '18-Dec-2002' },
    { title: 'Inception', rating: 'PG-13', release_date: '16-Jul-2010' },
    { title: 'Star Wars: Episode V - The Empire Strikes Back', rating: 'PG', release_date: '20-Jun-1980' },
    { title: 'The Matrix', rating: 'R', release_date: '31-Mar-1999' },
    { title: 'Goodfellas', rating: 'R', release_date: '21-Sep-1990' },
    { title: "One Flew Over the Cuckoo's Nest", rating: 'R', release_date: '19-Nov-1975' },
    { title: 'Se7en', rating: 'R', release_date: '22-Sep-1995' },
    { title: 'Seven Samurai', rating: 'Not Rated', release_date: '19-Nov-1956' },
    { title: "It's a Wonderful Life", rating: 'PG', release_date: '07-Jan-1947' },
    { title: 'The Silence of the Lambs', rating: 'R', release_date: '14-Feb-1991' },
    { title: 'City of God', rating: 'R', release_date: '13-Feb-2004' },
    { title: 'Saving Private Ryan', rating: 'R', release_date: '24-Jul-1998' },
    { title: 'Life Is Beautiful', rating: 'PG-13', release_date: '12-Feb-1999' },
    { title: 'The Green Mile', rating: 'R', release_date: '10-Dec-1999' },
    { title: 'Star Wars: Episode IV - A New Hope', rating: 'PG', release_date: '25-May-1977' },
    { title: 'Terminator 2: Judgment Day', rating: 'R', release_date: '03-Jul-1991' },
    { title: 'Spirited Away', rating: 'PG', release_date: '28-Mar-2003' },
    { title: 'The Pianist', rating: 'R', release_date: '28-Mar-2003' },
    { title: 'Parasite', rating: 'R', release_date: '08-Nov-2019' },
    { title: 'Gladiator', rating: 'R', release_date: '05-May-2000' },
    { title: 'The Departed', rating: 'R', release_date: '06-Oct-2006' },
    { title: 'The Usual Suspects', rating: 'R', release_date: '15-Sep-1995' },
    { title: 'Léon: The Professional', rating: 'R', release_date: '18-Nov-1994' },
    { title: 'The Prestige', rating: 'PG-13', release_date: '20-Oct-2006' },
    { title: 'American History X', rating: 'R', release_date: '20-Nov-1998' },
    { title: 'Back to the Future', rating: 'PG', release_date: '03-Jul-1985' },
    { title: 'Whiplash', rating: 'R', release_date: '15-Oct-2014' },
    { title: 'The Intouchables', rating: 'R', release_date: '25-May-2012' },
    { title: 'Modern Times', rating: 'G', release_date: '21-Feb-1936' },
    { title: 'Grave of the Fireflies', rating: 'Not Rated', release_date: '26-Jul-1989' },
    { title: 'Psycho', rating: 'R', release_date: '08-Sep-1960' },
    { title: 'City Lights', rating: 'G', release_date: '07-Mar-1931' },
    { title: 'Once Upon a Time in the West', rating: 'PG-13', release_date: '28-May-1969' },
    { title: 'Rear Window', rating: 'PG', release_date: '01-Sep-1954' },
    { title: 'Alien', rating: 'R', release_date: '22-Jun-1979' },
    { title: 'Apocalypse Now', rating: 'R', release_date: '15-Aug-1979' },
    { title: 'Memento', rating: 'R', release_date: '25-May-2001' },
    { title: 'Raiders of the Lost Ark', rating: 'PG', release_date: '12-Jun-1981' },
    { title: 'Django Unchained', rating: 'R', release_date: '25-Dec-2012' },
    { title: 'WALL·E', rating: 'G', release_date: '27-Jun-2008' },
    { title: 'The Lives of Others', rating: 'R', release_date: '30-Mar-2007' },
    { title: 'Sunset Blvd.', rating: 'Not Rated', release_date: '29-Sep-1950' },
    { title: 'Paths of Glory', rating: 'Not Rated', release_date: '25-Dec-1957' },
    { title: 'The Shining', rating: 'R', release_date: '13-Jun-1980' },
    { title: 'The Great Dictator', rating: 'G', release_date: '07-Mar-1941' },
    { title: 'Avengers: Infinity War', rating: 'PG-13', release_date: '27-Apr-2018' },
    { title: 'Witness for the Prosecution', rating: 'Not Rated', release_date: '06-Feb-1958' },
    { title: 'Aliens', rating: 'R', release_date: '18-Jul-1986' },
    { title: 'American Beauty', rating: 'R', release_date: '01-Oct-1999' },
    { title: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', rating: 'PG', release_date: '29-Jan-1964' },
    { title: 'Spider-Man: Into the Spider-Verse', rating: 'PG', release_date: '14-Dec-2018' },
    { title: 'The Dark Knight Rises', rating: 'PG-13', release_date: '20-Jul-2012' },
    { title: 'Oldboy', rating: 'R', release_date: '21-Nov-2003' },
    { title: 'Joker', rating: 'R', release_date: '04-Oct-2019' },
    { title: 'Amadeus', rating: 'PG', release_date: '19-Sep-1984' },
    { title: 'Toy Story', rating: 'G', release_date: '22-Nov-1995' },
    { title: 'Inglourious Basterds', rating: 'R', release_date: '21-Aug-2009' },
    { title: 'Coco', rating: 'PG', release_date: '22-Nov-2017' },
    { title: 'Braveheart', rating: 'R', release_date: '24-May-1995' },
    { title: 'The Boat', rating: 'R', release_date: '10-Feb-1982' },
    { title: 'Avengers: Endgame', rating: 'PG-13', release_date: '26-Apr-2019' },
    { title: 'Princess Mononoke', rating: 'PG-13', release_date: '17-Dec-1999' },
    { title: 'Good Will Hunting', rating: 'R', release_date: '09-Jan-1998' },
    { title: 'Your Name.', rating: 'PG', release_date: '07-Apr-2017' },
    { title: 'Once Upon a Time in America', rating: 'R', release_date: '22-Feb-1984' },
    { title: 'Toy Story 3', rating: 'G', release_date: '18-Jun-2010' },
    { title: 'Requiem for a Dream', rating: 'R', release_date: '15-Dec-2000' },
    { title: '3 Idiots', rating: 'PG-13', release_date: '23-Dec-2009' },
    { title: 'Singin\' in the Rain', rating: 'G', release_date: '11-Apr-1952' },
    { title: 'Star Wars: Episode VI - Return of the Jedi', rating: 'PG', release_date: '25-May-1983' },
    { title: '2001: A Space Odyssey', rating: 'G', release_date: '12-May-1968' },
    { title: 'Eternal Sunshine of the Spotless Mind', rating: 'R', release_date: '19-Mar-2004' },
    { title: 'The Hunt', rating: 'R', release_date: '22-Mar-2013' },
    { title: 'Reservoir Dogs', rating: 'R', release_date: '09-Oct-1992' },
    { title: 'Citizen Kane', rating: 'PG', release_date: '05-Sep-1941' },
    { title: 'Lawrence of Arabia', rating: 'Not Rated', release_date: '16-Dec-1962' },
    { title: 'M', rating: 'Not Rated', release_date: '31-Mar-1933' },
    { title: 'North by Northwest', rating: 'Not Rated', release_date: '28-Sep-1959' },
    { title: 'Vertigo', rating: 'PG', release_date: '22-May-1958' },
    { title: 'A Clockwork Orange', rating: 'R', release_date: '02-Feb-1972' },
    { title: 'The Apartment', rating: 'Not Rated', release_date: '21-Jun-1960' },
    { title: 'Double Indemnity', rating: 'Not Rated', release_date: '06-Jul-1944' },
    { title: 'Full Metal Jacket', rating: 'R', release_date: '10-Jul-1987' },
    { title: 'Scarface', rating: 'R', release_date: '09-Dec-1983' },
    { title: 'Ikiru', rating: 'Not Rated', release_date: '29-Mar-1960' },
    { title: 'Hamilton', rating: 'PG-13', release_date: '03-Jul-2020' },
    { title: 'To Kill a Mockingbird', rating: 'Not Rated', release_date: '13-Feb-1963' }
  ]

  all_movies = more_movies + top_100_movies
  
  puts "Seeding database with movies..."
  all_movies.each do |movie|
    Movie.find_or_create_by!(movie)
  end
  puts "Seeding complete!"